//
// Generated file, do not edit! Created by nedtool 6.0 from src/LoRaFrames/LoRaAppUplinkFrame.msg.
//

#ifndef __LORAAPPUPLINKFRAME_M_H
#define __LORAAPPUPLINKFRAME_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



struct LoRaControlUplink;
class LoRaAppUplinkFrame;
/**
 * Struct generated from src/LoRaFrames/LoRaAppUplinkFrame.msg:1 by nedtool.
 */
struct LoRaControlUplink
{
    LoRaControlUplink();
    bool FOptsLen[4];
    bool ClassB = false;
    bool ACK = false;
    bool ADRACKReq = false;
    bool ADR = false;
};

// helpers for local use
void __doPacking(omnetpp::cCommBuffer *b, const LoRaControlUplink& a);
void __doUnpacking(omnetpp::cCommBuffer *b, LoRaControlUplink& a);

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LoRaControlUplink& obj) { __doPacking(b, obj); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LoRaControlUplink& obj) { __doUnpacking(b, obj); }

/**
 * Class generated from <tt>src/LoRaFrames/LoRaAppUplinkFrame.msg:19</tt> by nedtool.
 * <pre>
 * packet LoRaAppUplinkFrame
 * {
 *     uint8_t deviceAddress[4];
 *     LoRaControlUplink control;
 *     uint16_t counter;
 *     uint8_t port;
 *     uint8_t payload[11]; // based on data rate and region specs (min 11 bytes)
 * }
 * </pre>
 */
class LoRaAppUplinkFrame : public ::omnetpp::cPacket
{
  protected:
    uint8_t deviceAddress[4] = {0};
    LoRaControlUplink control;
    uint16_t counter = 0;
    uint8_t port = 0;
    uint8_t payload[11] = {0};

  private:
    void copy(const LoRaAppUplinkFrame& other);

  protected:
    bool operator==(const LoRaAppUplinkFrame&) = delete;

  public:
    LoRaAppUplinkFrame(const char *name=nullptr, short kind=0);
    LoRaAppUplinkFrame(const LoRaAppUplinkFrame& other);
    virtual ~LoRaAppUplinkFrame();
    LoRaAppUplinkFrame& operator=(const LoRaAppUplinkFrame& other);
    virtual LoRaAppUplinkFrame *dup() const override {return new LoRaAppUplinkFrame(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual size_t getDeviceAddressArraySize() const;
    virtual uint8_t getDeviceAddress(size_t k) const;
    virtual void setDeviceAddress(size_t k, uint8_t deviceAddress);
    virtual const LoRaControlUplink& getControl() const;
    virtual LoRaControlUplink& getControlForUpdate() { return const_cast<LoRaControlUplink&>(const_cast<LoRaAppUplinkFrame*>(this)->getControl());}
    virtual void setControl(const LoRaControlUplink& control);
    virtual uint16_t getCounter() const;
    virtual void setCounter(uint16_t counter);
    virtual uint8_t getPort() const;
    virtual void setPort(uint8_t port);
    virtual size_t getPayloadArraySize() const;
    virtual uint8_t getPayload(size_t k) const;
    virtual void setPayload(size_t k, uint8_t payload);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const LoRaAppUplinkFrame& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, LoRaAppUplinkFrame& obj) {obj.parsimUnpack(b);}

#endif // ifndef __LORAAPPUPLINKFRAME_M_H

